name: Master Workflow
on:
  push:
    branches:
    - master
jobs:
  build_and_test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        uses: actions/setup-node@master
        with:
          version: '12.9.0'
      - name: Checkout
        uses: actions/checkout@master
      - name: install
        run: npm install
      - name: test
        run: npm run test:ci
  initialize:
    name: Initialize
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: initialize
        uses: hashicorp/terraform-github-actions/init@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          TF_ACTION_WORKING_DIR: ./infrastructure/terraform
      - name: apply
        uses: hashicorp/terraform-github-actions/apply@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          TF_ACTION_WORKING_DIR: ./infrastructure/terraform
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        uses: actions/setup-node@master
        with:
          version: '12.9.0'
      - name: Checkout
        uses: actions/checkout@master
      - name: install
        run: npm install
      - name: build
        run: npm run build
      - name: sync
        uses: actions/aws/cli@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        with:
          args: aws s3 sync ./build s3://beerrun.virtualmadden.dev
      - name: cache
        uses: actions/aws/cli@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        with:
          args: aws s3 cp ./build/index.html s3://beerrun.virtualmadden.dev/index.html --cache-control max-age=0
